// Character-to-Franchise Mapping for Disney Lorcana cards
// Official Lorcana card APIs (lorcanajson.org) do not include Disney franchise metadata,
// so this map derives the franchise based on character names.

export const CHARACTER_FRANCHISE_MAP: Record<string, string> = {
    Elsa: 'Frozen',
    Anna: 'Frozen',
    Kristoff: 'Frozen',
    Olaf: 'Frozen',
    Sven: 'Frozen',
    Hans: 'Frozen',
    Marshmallow: 'Frozen',
    Bruni: 'Frozen',
    Gale: 'Frozen',
    Nokk: 'Frozen',
    Yelena: 'Frozen',
    Honeymaren: 'Frozen',
    Ryder: 'Frozen',
    'Buzz Lightyear': 'Toy Story',
    Woody: 'Toy Story',
    Jessie: 'Toy Story',
    Rex: 'Toy Story',
    'Slinky Dog': 'Toy Story',
    Bullseye: 'Toy Story',
    Hamm: 'Toy Story',
    'Squeeze Toy Aliens': 'Toy Story',
    Aliens: 'Toy Story',
    Zurg: 'Toy Story',
    Al: 'Toy Story',
    Lotso: 'Toy Story',
    'Green Army Men': 'Toy Story',
    Sarge: 'Toy Story',
    'Carl Fredricksen': 'Up',
    'Ellie Fredricksen': 'Up',
    Russell: 'Up',
    Dug: 'Up',
    Kevin: 'Up',
    Alpha: 'Up',
    Beta: 'Up',
    Gamma: 'Up',
    Stitch: 'Lilo & Stitch',
    Lilo: 'Lilo & Stitch',
    Nani: 'Lilo & Stitch',
    David: 'Lilo & Stitch',
    Jumba: 'Lilo & Stitch',
    Pleakley: 'Lilo & Stitch',
    Gantu: 'Lilo & Stitch',
    Reuben: 'Lilo & Stitch',
    Angel: 'Lilo & Stitch',
    Leroy: 'Lilo & Stitch',
    'Sparky (625)': 'Lilo & Stitch',
    'Grand Councilwoman': 'Lilo & Stitch',
    Moana: 'Moana',
    Maui: 'Moana',
    Heihei: 'Moana',
    Pua: 'Moana',
    Tamatoa: 'Moana',
    TeFiti: 'Moana',
    TeKā: 'Moana',
    ChiefTui: 'Moana',
    Sina: 'Moana',
    GrammaTala: 'Moana',
    Kakamora: 'Moana',
    Mickey: 'Mickey & Friends',
    Minnie: 'Mickey & Friends',
    Donald: 'Mickey & Friends',
    Daisy: 'Mickey & Friends',
    Goofy: 'Mickey & Friends',
    Pluto: 'Mickey & Friends',
    Clarabelle: 'Mickey & Friends',
    Horace: 'Mickey & Friends',
    Pete: 'Mickey & Friends',
    'Chip (Squirrel)': 'Mickey & Friends',
    Dale: 'Mickey & Friends',
    Oswald: 'Mickey & Friends',
    Ortensia: 'Mickey & Friends',
    Simba: 'The Lion King',
    Nala: 'The Lion King',
    Mufasa: 'The Lion King',
    Scar: 'The Lion King',
    Timon: 'The Lion King',
    Pumbaa: 'The Lion King',
    Rafiki: 'The Lion King',
    Zazu: 'The Lion King',
    Shenzi: 'The Lion King',
    Banzai: 'The Lion King',
    Ed: 'The Lion King',
    Kiara: 'The Lion King',
    Kovù: 'The Lion King',
    Kion: 'The Lion King',
    Aladdin: 'Aladdin',
    Jasmine: 'Aladdin',
    Genie: 'Aladdin',
    Jafar: 'Aladdin',
    Iago: 'Aladdin',
    Abu: 'Aladdin',
    Rajah: 'Aladdin',
    Sultan: 'Aladdin',
    'Magic Carpet': 'Aladdin',
    Gazeem: 'Aladdin',
    Peddler: 'Aladdin',
    Cassim: 'Aladdin',
    "Sa'luk": 'Aladdin',
    Ariel: 'The Little Mermaid',
    Eric: 'The Little Mermaid',
    Triton: 'The Little Mermaid',
    Ursula: 'The Little Mermaid',
    Sebastian: 'The Little Mermaid',
    Flounder: 'The Little Mermaid',
    Scuttle: 'The Little Mermaid',
    'Flotsam & Jetsam': 'The Little Mermaid',
    Flotsam: 'The Little Mermaid',
    Jetsam: 'The Little Mermaid',
    ChefLouis: 'The Little Mermaid',
    Morgana: 'The Little Mermaid',
    Melody: 'The Little Mermaid',
    Belle: 'Beauty and the Beast',
    Beast: 'Beauty and the Beast',
    Gaston: 'Beauty and the Beast',
    Lumiere: 'Beauty and the Beast',
    Cogsworth: 'Beauty and the Beast',
    'Mrs. Potts': 'Beauty and the Beast',
    Chip: 'Beauty and the Beast',
    Lefou: 'Beauty and the Beast',
    Maurice: 'Beauty and the Beast',
    Wardrobe: 'Beauty and the Beast',
    Fifi: 'Beauty and the Beast',
    Enchantress: 'Beauty and the Beast',
    'Peter Pan': 'Peter Pan',
    Wendy: 'Peter Pan',
    John: 'Peter Pan',
    Michael: 'Peter Pan',
    'Tinker Bell': 'Peter Pan',
    'Captain Hook': 'Peter Pan',
    'Mr. Smee': 'Peter Pan',
    'Tick-Tock': 'Peter Pan',
    'Lost Boys': 'Peter Pan',
    Slightly: 'Peter Pan',
    Nibs: 'Peter Pan',
    Cubby: 'Peter Pan',
    Twins: 'Peter Pan',
    'Tiger Lily': 'Peter Pan',
    Hercules: 'Hercules',
    Megara: 'Hercules',
    Philoctetes: 'Hercules',
    Hades: 'Hercules',
    Pain: 'Hercules',
    Panic: 'Hercules',
    Pegasus: 'Hercules',
    Zeus: 'Hercules',
    Hera: 'Hercules',
    Hermes: 'Hercules',
    Amphitryon: 'Hercules',
    Alcmene: 'Hercules',
    Mulan: 'Mulan',
    Mushu: 'Mulan',
    Shang: 'Mulan',
    ShanYu: 'Mulan',
    Yao: 'Mulan',
    Ling: 'Mulan',
    ChienPo: 'Mulan',
    FaLi: 'Mulan',
    FaZhou: 'Mulan',
    GrandmotherFa: 'Mulan',
    Matchmaker: 'Mulan',
    Rapunzel: 'Tangled',
    Flynn: 'Tangled',
    Pascal: 'Tangled',
    Maximus: 'Tangled',
    Gothel: 'Tangled',
    'Snuggly Duckling': 'Tangled',
    HookFoot: 'Tangled',
    BigNose: 'Tangled',
    Vladimir: 'Tangled',
    Cinderella: 'Cinderella',
    'Prince Charming': 'Cinderella',
    'Fairy Godmother': 'Cinderella',
    'Lady Tremaine': 'Cinderella',
    Anastasia: 'Cinderella',
    Drizella: 'Cinderella',
    Jaq: 'Cinderella',
    Gus: 'Cinderella',
    Lucifer: 'Cinderella',
    'Bruno (Dog)': 'Cinderella',
    'Snow White': 'Snow White',
    Doc: 'Snow White',
    Grumpy: 'Snow White',
    Happy: 'Snow White',
    Sleepy: 'Snow White',
    Bashful: 'Snow White',
    Sneezy: 'Snow White',
    Dopey: 'Snow White',
    'The Queen': 'Snow White',
    'Evil Queen': 'Snow White',
    'Huntsman (Snow White)': 'Snow White',
    'Prince (Snow White)': 'Snow White',
    'Sleeping Beauty': 'Sleeping Beauty',
    Aurora: 'Sleeping Beauty',
    Phillip: 'Sleeping Beauty',
    Maleficent: 'Sleeping Beauty',
    Flora: 'Sleeping Beauty',
    Fauna: 'Sleeping Beauty',
    Merryweather: 'Sleeping Beauty',
    Diablo: 'Sleeping Beauty',
    'King Stefan': 'Sleeping Beauty',
    'King Hubert': 'Sleeping Beauty',
    Pinocchio: 'Pinocchio',
    Geppetto: 'Pinocchio',
    Jiminy: 'Pinocchio',
    'Blue Fairy': 'Pinocchio',
    'Honest John': 'Pinocchio',
    Gideon: 'Pinocchio',
    Stromboli: 'Pinocchio',
    Monstro: 'Pinocchio',
    Figaro: 'Pinocchio',
    Cleo: 'Pinocchio',
    Robin: 'Robin Hood',
    Marian: 'Robin Hood',
    'Little John': 'Robin Hood',
    FriarTuck: 'Robin Hood',
    'Prince John': 'Robin Hood',
    Hiss: 'Robin Hood',
    'Sheriff of Nottingham': 'Robin Hood',
    Nutsy: 'Robin Hood',
    Trigger: 'Robin Hood',
    Skippy: 'Robin Hood',
    Toby: 'Robin Hood',
    Tagalong: 'Robin Hood',
    Bambi: 'Bambi',
    Thumper: 'Bambi',
    Flower: 'Bambi',
    Faline: 'Bambi',
    'Great Prince': 'Bambi',
    Dumbo: 'Dumbo',
    Timothy: 'Dumbo',
    'Ringmaster (Dumbo)': 'Dumbo',
    Alice: 'Alice in Wonderland',
    'Mad Hatter': 'Alice in Wonderland',
    'March Hare': 'Alice in Wonderland',
    'Cheshire Cat': 'Alice in Wonderland',
    'White Rabbit': 'Alice in Wonderland',
    'Queen of Hearts': 'Alice in Wonderland',
    'King of Hearts': 'Alice in Wonderland',
    Caterpillar: 'Alice in Wonderland',
    Tweedledee: 'Alice in Wonderland',
    Tweedledum: 'Alice in Wonderland',
    'Doorknob (Alice)': 'Alice in Wonderland',
    Walrus: 'Alice in Wonderland',
    Carpenter: 'Alice in Wonderland',
    Dodo: 'Alice in Wonderland',
    Winnie: 'Winnie the Pooh',
    Pooh: 'Winnie the Pooh',
    Piglet: 'Winnie the Pooh',
    Tigger: 'Winnie the Pooh',
    Eeyore: 'Winnie the Pooh',
    Rabbit: 'Winnie the Pooh',
    Owl: 'Winnie the Pooh',
    Kanga: 'Winnie the Pooh',
    Roo: 'Winnie the Pooh',
    Christopher: 'Winnie the Pooh',
    Gopher: 'Winnie the Pooh',
    Tarzan: 'Tarzan',
    Jane: 'Tarzan',
    Clayton: 'Tarzan',
    Kala: 'Tarzan',
    Kerchak: 'Tarzan',
    Tantor: 'Tarzan',
    Terk: 'Tarzan',
    Quasimodo: 'The Hunchback of Notre Dame',
    Esmeralda: 'The Hunchback of Notre Dame',
    Phoebus: 'The Hunchback of Notre Dame',
    Frollo: 'The Hunchback of Notre Dame',
    Clopin: 'The Hunchback of Notre Dame',
    Hugo: 'The Hunchback of Notre Dame',
    Victor: 'The Hunchback of Notre Dame',
    Laverne: 'The Hunchback of Notre Dame',
    Atlantis: 'Atlantis: The Lost Empire',
    Milo: 'Atlantis: The Lost Empire',
    Kida: 'Atlantis: The Lost Empire',
    Rourke: 'Atlantis: The Lost Empire',
    Helga: 'Atlantis: The Lost Empire',
    Sweet: 'Atlantis: The Lost Empire',
    Vinny: 'Atlantis: The Lost Empire',
    Audrey: 'Atlantis: The Lost Empire',
    Mole: 'Atlantis: The Lost Empire',
    Cookie: 'Atlantis: The Lost Empire',
    Treasure: 'Treasure Planet',
    Jim: 'Treasure Planet',
    Silver: 'Treasure Planet',
    Amelia: 'Treasure Planet',
    Delbert: 'Treasure Planet',
    'B.O.B.': 'Treasure Planet',
    Morph: 'Treasure Planet',
    Scroop: 'Treasure Planet',
    'Brother Bear': 'Brother Bear',
    Kenai: 'Brother Bear',
    Koda: 'Brother Bear',
    Rutt: 'Brother Bear',
    Tuke: 'Brother Bear',
    Denahi: 'Brother Bear',
    Sitka: 'Brother Bear',
    Tanana: 'Brother Bear',
    'Meet the Robinsons': 'Meet the Robinsons',
    Lewis: 'Meet the Robinsons',
    Wilbur: 'Meet the Robinsons',
    Bowler: 'Meet the Robinsons',
    Doris: 'Meet the Robinsons',
    Goob: 'Meet the Robinsons',
    Bolt: 'Bolt',
    Mittens: 'Bolt',
    Rhino: 'Bolt',
    Penny: 'Bolt',
    Tiana: 'The Princess and the Frog',
    Naveen: 'The Princess and the Frog',
    Facilier: 'The Princess and the Frog',
    Ray: 'The Princess and the Frog',
    Louis: 'The Princess and the Frog',
    Mama: 'The Princess and the Frog',
    Charlotte: 'The Princess and the Frog',
    Lawrence: 'The Princess and the Frog',
    BigDaddy: 'The Princess and the Frog',
    Juju: 'The Princess and the Frog',
};
